create table if not exists public.users (
    id uuid default gen_random_uuid() primary key,
    email text unique not null,
    password text not null,
    role text not null default 'student',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.student_profiles (
    id uuid default gen_random_uuid() primary key,
    user_id uuid unique references public.users(id) on delete cascade,
    name text,
    roll_no text unique,
    dob date,
    blood_group text,
    department text,
    year text,
    section text,
    admission_mode text,
    mobile text,
    whatsapp text,
    father_name text,
    father_contact text,
    mother_name text,
    mother_contact text,
    address text,
    district text,
    floor integer,
    room_no text,
    fee_mode text,
    passport_photo_url text,
    id_card_photo_url text,
    fees_receipt_url text,
    can_apply boolean default true,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.allocations (
    id bigint generated by default as identity primary key,
    email text,
    name text,
    reg_no text unique,
    department text,
    hostel text,
    floor text,
    room_number text,
    bed_number integer,
    status text,
    receipt_url text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.leave_applications (
    id bigint generated by default as identity primary key,
    email text,
    user_id uuid references public.users(id) on delete cascade,
    name text,
    roll_number text,
    branch text,
    year text,
    semester text,
    hostel_name text,
    room_number text,
    date_of_stay date,
    time text,
    reason text,
    student_mobile text,
    parent_mobile text,
    informed_advisor text,
    advisor_name text,
    advisor_mobile text,
    student_signature_url text,
    admin_signature_url text,
    status text default 'pending',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.hostel_rules (
    id integer default 1 primary key,
    general_rules jsonb,
    mess_timings jsonb,
    gate_timings jsonb,
    prohibited_items jsonb,
    consequences jsonb
);

create table if not exists public.weekly_menu (
    day text primary key,
    morning text,
    breakfast text,
    lunch text,
    evening text,
    dinner text
);

create table if not exists public.feedbacks (
    id bigint generated by default as identity primary key,
    name text,
    roll_no text,
    department text,
    room_no text,
    feedback_type text,
    message text,
    urgency text,
    status text default 'pending',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists public.announcements (
    id bigint generated by default as identity primary key,
    title text,
    content text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
